[package]
name = "secretcli"
version = "0.1.0"
authors = [
  "Guy Garcia <guysebastiangarcia@gmail.com>",
  "hydropump3 <3ki2fiay@anonaddy.me>",
]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["helpers"]
helpers = ["cosmwasm-std"]

[dependencies]
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.67"}
# lightweight crate that is safe to use for random label generation
# uses rand, but with small_rng feature flag so it does not import std and std_rng
# https://docs.rs/nanoid/latest/nanoid/
nanoid = "0.4.0"
colored = "2.0.0"

# Optional for now
cosmwasm-std = { git = "https://github.com/scrtlabs/cosmwasm", branch = "secret", optional = true }


